DATA:
  data_root: /data/datasets/Cityscapes/
  train_list: /data/datasets/Cityscapes/list/fine_train.txt
  val_list: /data/datasets/Cityscapes/list/fine_val.txt
  classes: 19

TRAIN:
  arch: psp
  layers: 50
  sync_bn: True # adopt syncbn or not
  # train_h: 713
  # train_w: 713
  train_h: 225
  train_w: 225
  scale_min: 0.5
  scale_max: 2.0
  rotate_min: -10
  rotate_max: 10
  zoom_factor: 8  # input size zoom_factor
  ignore_label: 255
  aux_weight: 0.4
  train_gpu: [0, 1]
  workers: 16  # data loader workers
  batch_size: 8 
  batch_size_val: 4 # batch size for validation during training, memory and speed tradeoff
  base_lr: 0.01
  power: 0.9
  epochs: 2
  start_epoch: 0
  momentum: 0.9
  weight_decay: 0.0001
  manual_seed:
  print_freq: 10
  save_freq: 1 
  save_path: exp/cityscapes/pspnet50/model
  weight:  # path to initial weight
  resume:  # path to latest checkpoint
  evaluate: True  # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend
Distributed:
  dist_url: tcp://127.0.0.1:6789
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  world_size: 1 # 分布式有1个主机
  rank: 0 # 分布式0号主机
